# Generated by Django 5.1.5 on 2025-03-01 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChatGPT', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chathistory',
            name='is_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='chathistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
