# Generated by Django 5.1.5 on 2025-03-04 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChatGPT', '0003_alter_chathistory_chat_input_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chathistory',
            options={'ordering': ['sequence']},
        ),
        migrations.AddField(
            model_name='chathistory',
            name='sequence',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chathistory',
            name='session_id',
            field=models.CharField(default='default', max_length=32),
        ),
    ]
